name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-version: ["18", "19"]

    name: Test with React ${{ matrix.react-version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install Dependencies
        run: |
          npm install
          npm install react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}

      - name: Linting
        run: npm run lint:check

      - name: Formatting
        run: npm run format:check

      - name: Unit tests
        run: npm test
